language: dart
sudo: false
dart:
  - stable

cache:
  directories:
    - $HOME/.pub-cache

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

dart_task:
  - test: --platform vm
  - dartanalyzer
  - dartfmt
