name: shortbow
description: Utility library for game programming
author: Matan Lurey <matan@lurey.org>
homepage: https://github.com/matanlurey/shortbow
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  meta: ^1.1.5

dev_dependencies:
  build_runner: ^0.9.1
  build_test: ^0.10.3
  build_web_compilers: ^0.4.0+4
  test: ^1.2.0
