name: shortbow
author: Matan Lurey <matan@lurey.org>
version: 0.0.0

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  meta: ^1.1.5

dev_dependencies:
  build_runner: ^0.8.8
  build_test: ^0.10.2+3
  build_web_compilers: ^0.4.0
  test: ^0.12.37
